name: ci
on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: latest

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle 8.10.2
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10.2

      - name: Run tests
        working-directory: app
        run: gradle test --no-daemon

  build_and_push_image:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute lowercase image name
        run: echo "IMAGE_REF=${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ env.IMAGE_REF }}
  deploy_to_vm:
    if: github.ref == 'refs/heads/main'
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Charge la clé privée depuis le secret SSH_KEY
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          # ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}   # si ta clé a une passphrase

      # (Optionnel) Smoke test SSH
      - name: SSH smoke test
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
              "${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}" \
              'echo OK && hostname && whoami'

      # Déploiement
      - name: Remote deploy
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=accept-new \
              "${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}" \
              'cd /opt/brokerx && ./deploy.sh && docker compose -f docker-compose.prod.yml ps'
